//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzNginx.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NginxResource
    {
        public int Id { get; set; }
        public string ResourceName { get; set; }
        public string ResourceType { get; set; }
        public string ResourceGroup { get; set; }
        public string Location { get; set; }
        public NginxResourceStatus Status { get; set; }
        public string NginxVersion { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string TagsSerialized { get; set; }
        public string UserSubscriptionId { get; set; }
    }
}
