//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzNginx.DAL
{
    using System;
    
    public enum NginxResourceStatus : int
    {
        Active = 0,
        Creating = 1,
        CreateFailed = 2,
        Enabling = 3,
        Enabled = 4,
        EnableFailed = 5,
        Disabling = 6,
        Disabled = 7,
        DisableFailed = 8,
        Deleting = 9,
        Deleted = 10,
        DeleteFailed = 11,
        Moving = 12,
        Moved = 13
    }
}
